language:       ocaml
before_install: sudo apt-get update -qq
install:        
  - sudo apt-get install -y ocaml ocaml-nox ocaml-native-compilers camlp4-extra time
  - git clone https://github.com/UniMath/UniMath
  - cd UniMath && make && make install
  - export PATH=$PATH:$PWD/sub/coq/bin/
script:
  - make

